Seedfile for The Wronged
ChaelCodes/HuntersKeepers pull request #181
Opened 2020-10-03 17:37 UTC by bipster

## Description of Feature or Issue
closes 112

:card_file_box:  `wronged.seeds.rb` seed data.

## Thoughts/Issues/Questions
:construction:  "DIY Surgery" 7-9 roll description includes inline bullet points, vs. embedding HTML newlines in the database
:construction:  Gear: "Sawn-off shotgun" has a "hand/close" tag -- should these be separated, vs. one?
:construction:  Gear: Do signature weapons and practical weapons need a differentiable property?
:construction:  Improvement: "Create a second hunter to play as well with this one" needs a type
:construction:  Improvement: "Mark two of the basic moves as advanced" & "Mark another two of the basic moves as advanced" -- should these diverge from the manual to have the same name with `stat_limit: 0|-1`?
:construction:  Improvement: "You track down the specific monster(s) responsible for your loss. The Keeper must make the next mystery about them" needs a type
:construction:  Improvement: "Change the target of your vengeful rage. Pick a new monster breed: I know my prey now applies to them instead." needs a type

## Tangential Changes
:memo:  Added `docker-compose` command to reset the DB w/ seed file to the contributing doc
:bug:  `chosen.seeds.rb`: Weird and Tough improvements had their ratings switched
:pencil2:  `chosen.seeds.rb`: Converted smart-quote for consistency and to avoid encoding issues

## User-Facing Changes
![image](https://user-images.githubusercontent.com/796596/94997875-08674000-057c-11eb-965d-20612caf2c96.png)

2020-10-04 00:09 UTC, ChaelCodes commented
> 🚧  "DIY Surgery" 7-9 roll description includes inline bullet points, vs. embedding HTML newlines in the database
In the past, we've used newlines and bullet points. It's a little inconsistent. There's nothing in the repo yet to evaluate and parse HTML. What you've got here presents fine.
> 🚧  Gear: "Sawn-off shotgun" has a "hand/close" tag -- should these be separated, vs. one?
They should be one. I want to copy the book, inconsistencies and all, wherever possible.
> 🚧  Gear: Do signature weapons and practical weapons need a differentiable property?
This is a more complicated question than you may think. The differentiable property is being handled in the playbook <=> gear relationship, which will be heavily impacted by https://github.com/ChaelCodes/HuntersKeepers/pull/129 . This is a harder PR to review, and I've been procrastinating on it, but it's the answer to this problem.
> 🚧  Improvement: "Create a second hunter to play as well with this one" needs a type
Yes. https://github.com/ChaelCodes/HuntersKeepers/issues/100 I haven't finished this yet.
> 🚧  Improvement: "Mark two of the basic moves as advanced" & "Mark another two of the basic moves as advanced" -- should these diverge from the manual to have the same name with stat_limit: 0|-1?
> 🚧  Improvement: "You track down the specific monster(s) responsible for your loss. The Keeper must make the next mystery about them" needs a type
Yes. This one doesn't have an issue though. Let's make one!
> 🚧  Improvement: "Change the target of your vengeful rage. Pick a new monster breed: I know my prey now applies to them instead." needs a type
Yes! Same situation as the track down monster. Maybe these could be descriptive improvements? Like we have descriptive moves?

OH! Can we make an improvement with no type? I tried this using Improvement, and it totally worked! These are very descriptive and impact story rather than mechanics, so let's use Improvement as the class!

2020-10-04 00:19 UTC, ChaelCodes requested changes
When the `six_and_under` is missing, I make one up that sounds reasonable and vague. Also, those AnotherMove I pointed out should be PlaybookMoves.

Thank you for your thorough feedback on the seedfiles! Also, I love the Docker documentation, and that you fixed some details in the Chosen seedfile.

2020-10-04 00:19 UTC, ChaelCodes commented on CONTRIBUTING.md
> +
I love this.

2020-10-04 00:19 UTC, ChaelCodes commented on db/seeds/playbooks/wronged.seeds.rb
> +     type: 'Moves::Rollable',
It looks like this one is missing a six_and_under.

2020-10-04 00:19 UTC, ChaelCodes commented on db/seeds/playbooks/wronged.seeds.rb
> +      type: 'Improvements::AnotherMove',
I believe this should actually be a Improvements::PlaybookMove because it belongs to your playbook, not another playbook.

2020-10-04 00:19 UTC, ChaelCodes commented on db/seeds/playbooks/wronged.seeds.rb
> +      type: 'Improvements::AnotherMove',
I believe this should actually be a Improvements::PlaybookMove because it belongs to your playbook, not another playbook.

2020-10-04 00:19 UTC, ChaelCodes commented on db/seeds/playbooks/wronged.seeds.rb
> +      advanced: true
This should work. I believe it'll automatically be set to Improvement.

2020-10-04 03:13 UTC, bipster commented on db/seeds/playbooks/wronged.seeds.rb
> +  # Note: Signature weapon could also be:
> Where did this ruling come from?

Ah, I meant to call that out in the PR description as well.  One of the Gear options for Wronged is:

![image](https://user-images.githubusercontent.com/796596/95006051-d088e880-05cd-11eb-9b1c-7313ee9170ce.png)

I wasn't sure how to fit ^ into the existing Gear structure.  i.e. conditional Harm and variable tags.

2020-10-05 00:21 UTC, ChaelCodes commented on db/seeds/playbooks/wronged.seeds.rb
> +  # Note: Signature weapon could also be:
This feels like a custom weapon, kindof like the Chosen has, which we don't currently support. :+1:

2020-10-05 00:23 UTC, ChaelCodes approved these changes
Thank you so much for tackling a Seedfile!! They're a little onerous, but it's really important to players.

2020-10-05 00:23 UTC, merged